
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\dipes\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x734")
window.configure(bg = "#75E6DA")


canvas = Canvas(
    window,
    bg = "#75E6DA",
    height = 734,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    368.0,
    image=image_image_1
)

canvas.create_rectangle(
    631.0,
    366.0,
    1077.0,
    451.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    155.0,
    93.0,
    1115.0,
    627.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    155.0,
    93.0,
    569.0,
    627.0,
    fill="#2919D6",
    outline="")

canvas.create_rectangle(
    629.0,
    242.0,
    1075.0,
    322.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    853.5,
    404.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=656.0,
    y=377.0,
    width=395.0,
    height=52.0
)

canvas.create_text(
    645.0,
    208.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    185.0,
    307.0,
    anchor="nw",
    text="WELCOME",
    fill="#FFFFFF",
    font=("Inter Bold", 64 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    853.5,
    279.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=656.0,
    y=252.0,
    width=395.0,
    height=52.0
)

canvas.create_text(
    645.0,
    337.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_rectangle(
    704.0,
    140.0,
    1024.0,
    182.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    780.0,
    142.0,
    anchor="nw",
    text="Login/Signup",
    fill="#000000",
    font=("Inter SemiBold", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=780.0,
    y=446.0,
    width=196.0,
    height=66.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=766.0,
    y=512.0,
    width=243.0,
    height=63.0
)
window.resizable(True,True)
window.mainloop()
